image: python:3.9

stages:
  - test

before_script:
  - python -m pip install --upgrade pip
  - pip install pytest -r dev_requirements.txt

pytest:
  stage: test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
