# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Open-ALAQS
                                 A QGIS plugin
 An open-source local air quality model

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-09-06
        copyright            : (C) 2019 by Eurocontrol
        email                : open-alaqs@eurocontrol.int
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenALAQS class from file OpenALAQS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .openalaqs import Open_Alaqs
    return Open_Alaqs(iface)
