"""
This is a file that contains some of the variables that can be changed to change
the appearance of a study created within ALAQS.
"""

# Area Sources
AREA_FILL_COLOR = '255,51,51'
AREA_BORDER_COLOR = '0,0,0,100'
AREA_LABEL_ENABLED = False
AREA_LABEL_POSITION = 1
AREA_LABEL_FONT = 'Arial'
AREA_LABEL_FONT_SIZE = 8

# Building sources
BUILDING_FILL_COLOR = '168,168,168'
BUILDING_BORDER_COLOR = '0,0,0,255'
BUILDING_LABEL_ENABLED = False
BUILDING_LABEL_POSITION = 1
BUILDING_LABEL_FONT = 'Arial'
BUILDING_LABEL_FONT_SIZE = 8

# Gates
GATE_FILL_COLOR = '255,153,51'
GATE_BORDER_COLOR = '0,0,0,255'
GATE_LABEL_ENABLED = False
GATE_LABEL_POSITION = 1
GATE_LABEL_FONT = 'Arial'
GATE_LABEL_FONT_SIZE = 8

# Parking
PARKING_FILL_COLOR = '100,149,237'
PARKING_BORDER_COLOR = '0,0,0,255'
PARKING_LABEL_ENABLED = False
PARKING_LABEL_POSITION = 1
PARKING_LABEL_FONT = 'Arial'
PARKING_LABEL_FONT_SIZE = 8

# Roadway
ROADWAY_LINE_COLOR = '255,255,0'
ROADWAY_LINE_WIDTH = '0.75'
ROADWAY_LABEL_ENABLED = False
ROADWAY_LABEL_POSITION = 1
ROADWAY_LABEL_FONT = 'Arial'
ROADWAY_LABEL_FONT_SIZE = 8

# Taxiway
TAXIWAY_LINE_COLOR = '46,255,53'
TAXIWAY_LINE_WIDTH = '0.5'
TAXIWAY_LABEL_ENABLED = False
TAXIWAY_LABEL_POSITION = 1
TAXIWAY_LABEL_FONT = 'Arial'
TAXIWAY_LABEL_FONT_SIZE = 8

# Runway
RUNWAY_LINE_COLOR = '235,235,235'
RUNWAY_LINE_WIDTH = '2'
RUNWAY_LABEL_ENABLED = False
RUNWAY_LABEL_POSITION = 1
RUNWAY_LABEL_FONT = 'Arial'
RUNWAY_LABEL_FONT_SIZE = 8

# Spatialite extension
SPATIALTE_EXTENSION_FOLDER = "spatialite-4.0.0-DLL/"
SPATIALTE_EXTENSION_LIB = SPATIALTE_EXTENSION_FOLDER + "mod_spatialite.dll"
