DROP TABLE IF EXISTS "default_vehicle_nox_ef";

CREATE TABLE "default_vehicle_nox_ef" (
  "oid" INTEGER PRIMARY KEY, 
  "vehicle_type" VARCHAR(50), 
  "class" VARCHAR(50), 
  "legislation" VARCHAR(50), 
  "a1" DOUBLE PRECISION NULL DEFAULT 0, 
  "b1" DOUBLE PRECISION NULL DEFAULT 0, 
  "c1" DOUBLE PRECISION NULL DEFAULT 0, 
  "d1" DOUBLE PRECISION NULL DEFAULT 0, 
  "e1" DOUBLE PRECISION NULL DEFAULT 0, 
  "f1" DOUBLE PRECISION NULL DEFAULT 0, 
  "g1" DOUBLE PRECISION NULL DEFAULT 0, 
  "h1" DOUBLE PRECISION NULL DEFAULT 0, 
  "corr1" DOUBLE PRECISION NULL DEFAULT 0, 
  "a2" DOUBLE PRECISION NULL DEFAULT 0, 
  "b2" DOUBLE PRECISION NULL DEFAULT 0, 
  "c2" DOUBLE PRECISION NULL DEFAULT 0, 
  "d2" DOUBLE PRECISION NULL DEFAULT 0, 
  "e2" DOUBLE PRECISION NULL DEFAULT 0, 
  "f2" DOUBLE PRECISION NULL DEFAULT 0, 
  "g2" DOUBLE PRECISION NULL DEFAULT 0, 
  "h2" DOUBLE PRECISION NULL DEFAULT 0, 
  "corr2" DOUBLE PRECISION NULL DEFAULT 0
);