DROP TABLE IF EXISTS "default_aircraft_engine_ei";

CREATE TABLE "default_aircraft_engine_ei" (
  "oid" INTEGER PRIMARY KEY, 
  "engine_type" VARCHAR(1), 
  "engine_full_name" TEXT, 
  "engine_name" TEXT, 
  "thrust" DECIMAL, 
  "mode" VARCHAR(2), 
  "fuel_kg_sec" DECIMAL, 
  "co_ei" DECIMAL, 
  "hc_ei" DECIMAL, 
  "nox_ei" DECIMAL, 
  "sox_ei" DECIMAL, 
  "pm10_ei" DECIMAL, 
  "p1_ei" DECIMAL, 
  "p2_ei" INTEGER, 
  "smoke_number" DECIMAL, 
  "smoke_number_maximum" DECIMAL, 
  "fuel_type" TEXT, 
  "manufacturer" TEXT, 
  "source" TEXT, 
  "remark" TEXT, 
  "status" TEXT, 
  "engine_name_type" TEXT, 
  "coolant" VARCHAR(5), 
  "combustion_technology" TEXT, 
  "technology_age" TEXT, 
  "pm10_prefoa3" DECIMAL, 
  "pm10_nonvol" DECIMAL, 
  "pm10_sul" DECIMAL, 
  "pm10_organic" DECIMAL
);