# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_point_sources.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

jnkpth = "C:\\Users\\sstromat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\open_alaqs\\alaqs_core"
import sys
sys.path.append(jnkpth)
import alaqsdblite
#import alaqsutils

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 489)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setObjectName("label_47")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.source_id = QtWidgets.QLineEdit(Dialog)
        self.source_id.setObjectName("source_id")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.source_id)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.category = QtWidgets.QComboBox(self.tab)
        self.category.setObjectName("category")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.category)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2.setLayout(9, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.type = QtWidgets.QComboBox(self.tab)
        self.type.setEditable(False)
        self.type.setObjectName("type")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.type)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.substance = QtWidgets.QLineEdit(self.tab)
        self.substance.setObjectName("substance")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.substance)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.height = QtWidgets.QLineEdit(self.tab)
        self.height.setObjectName("height")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.height)
        self.ops_year = QtWidgets.QLineEdit(self.tab)
        self.ops_year.setObjectName("ops_year")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ops_year)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.temperature = QtWidgets.QLineEdit(self.tab)
        self.temperature.setObjectName("temperature")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.temperature)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.diameter = QtWidgets.QLineEdit(self.tab)
        self.diameter.setObjectName("diameter")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.diameter)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.velocity = QtWidgets.QLineEdit(self.tab)
        self.velocity.setObjectName("velocity")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.velocity)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.hour_profile = QtWidgets.QComboBox(self.tab_2)
        self.hour_profile.setObjectName("hour_profile")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hour_profile)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.daily_profile = QtWidgets.QComboBox(self.tab_2)
        self.daily_profile.setObjectName("daily_profile")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.daily_profile)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.month_profile = QtWidgets.QComboBox(self.tab_2)
        self.month_profile.setObjectName("month_profile")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.month_profile)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.co_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.co_kg_k.setObjectName("co_kg_k")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.co_kg_k)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.hc_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.hc_kg_k.setObjectName("hc_kg_k")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hc_kg_k)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.nox_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.nox_kg_k.setObjectName("nox_kg_k")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nox_kg_k)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sox_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.sox_kg_k.setObjectName("sox_kg_k")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sox_kg_k)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.pm10_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.pm10_kg_k.setObjectName("pm10_kg_k")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pm10_kg_k)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.p1_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.p1_kg_k.setObjectName("p1_kg_k")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.p1_kg_k)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.p2_kg_k = QtWidgets.QLineEdit(self.tab_3)
        self.p2_kg_k.setObjectName("p2_kg_k")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.p2_kg_k)
        self.tabWidget.addTab(self.tab_3, "")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.instudy = QtWidgets.QCheckBox(Dialog)
        self.instudy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.instudy.setChecked(True)
        self.instudy.setObjectName("instudy")
        self.horizontalLayout.addWidget(self.instudy)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.source_id, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.hour_profile)
        Dialog.setTabOrder(self.hour_profile, self.daily_profile)
        Dialog.setTabOrder(self.daily_profile, self.month_profile)
        Dialog.setTabOrder(self.month_profile, self.co_kg_k)
        Dialog.setTabOrder(self.co_kg_k, self.hc_kg_k)
        Dialog.setTabOrder(self.hc_kg_k, self.nox_kg_k)
        Dialog.setTabOrder(self.nox_kg_k, self.sox_kg_k)
        Dialog.setTabOrder(self.sox_kg_k, self.pm10_kg_k)
        Dialog.setTabOrder(self.pm10_kg_k, self.p1_kg_k)
        Dialog.setTabOrder(self.p1_kg_k, self.p2_kg_k)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenALAQS - Point Sources"))
        self.label_47.setText(_translate("Dialog", "Source Name"))
        self.label_6.setText(_translate("Dialog", "Category"))
        self.label_7.setText(_translate("Dialog", "Type"))
        self.label_8.setText(_translate("Dialog", "Substance"))
        self.label.setText(_translate("Dialog", "Height [m]"))
        self.label_3.setText(_translate("Dialog", "Temperature [°C]"))
        self.label_4.setText(_translate("Dialog", "Diameter [m]"))
        self.label_5.setText(_translate("Dialog", "Gas Velocity [m/s]"))
        self.label_2.setText(_translate("Dialog", "Units Per Year"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Parameters"))
        self.label_9.setText(_translate("Dialog", "Hourly"))
        self.label_10.setText(_translate("Dialog", "Daily"))
        self.label_11.setText(_translate("Dialog", "Monthly"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Profiles"))
        self.label_13.setText(_translate("Dialog", "CO [kg/unit]"))
        self.label_14.setText(_translate("Dialog", "HC [kg/unit]"))
        self.label_15.setText(_translate("Dialog", "NOx [kg/unit]"))
        self.label_16.setText(_translate("Dialog", "SOx [kg/unit]"))
        self.label_17.setText(_translate("Dialog", "PM10 [kg/unit]"))
        self.label_18.setText(_translate("Dialog", "P1 [kg/unit]"))
        self.label_19.setText(_translate("Dialog", "P2 [kg/unit]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Emissions"))
        self.instudy.setText(_translate("Dialog", "In Study"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

