# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_area_sources.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 448)
        self.formLayout_4 = QtWidgets.QFormLayout(Dialog)
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.instudy = QtWidgets.QCheckBox(Dialog)
        self.instudy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.instudy.setChecked(True)
        self.instudy.setObjectName("instudy")
        self.horizontalLayout_2.addWidget(self.instudy)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setObjectName("label_47")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.source_id = QtWidgets.QLineEdit(Dialog)
        self.source_id.setObjectName("source_id")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.source_id)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.unit_year = QtWidgets.QLineEdit(self.tab)
        self.unit_year.setObjectName("unit_year")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.unit_year)
        self.heightMLabel = QtWidgets.QLabel(self.tab)
        self.heightMLabel.setEnabled(True)
        self.heightMLabel.setObjectName("heightMLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.heightMLabel)
        self.height = QtWidgets.QLineEdit(self.tab)
        self.height.setEnabled(True)
        self.height.setText("")
        self.height.setObjectName("height")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.height)
        self.heatFluxMwLabel = QtWidgets.QLabel(self.tab)
        self.heatFluxMwLabel.setEnabled(True)
        self.heatFluxMwLabel.setObjectName("heatFluxMwLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.heatFluxMwLabel)
        self.heat_flux = QtWidgets.QLineEdit(self.tab)
        self.heat_flux.setEnabled(True)
        self.heat_flux.setText("")
        self.heat_flux.setObjectName("heat_flux")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.heat_flux)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.hourly_profile = QtWidgets.QComboBox(self.tab_2)
        self.hourly_profile.setEditable(False)
        self.hourly_profile.setObjectName("hourly_profile")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hourly_profile)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.daily_profile = QtWidgets.QComboBox(self.tab_2)
        self.daily_profile.setObjectName("daily_profile")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.daily_profile)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.monthly_profile = QtWidgets.QComboBox(self.tab_2)
        self.monthly_profile.setObjectName("monthly_profile")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.monthly_profile)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.co_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.co_kg_unit.setObjectName("co_kg_unit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.co_kg_unit)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.hc_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.hc_kg_unit.setObjectName("hc_kg_unit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hc_kg_unit)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.nox_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.nox_kg_unit.setObjectName("nox_kg_unit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nox_kg_unit)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sox_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.sox_kg_unit.setObjectName("sox_kg_unit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sox_kg_unit)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.pm10_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.pm10_kg_unit.setObjectName("pm10_kg_unit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pm10_kg_unit)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.p1_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.p1_kg_unit.setObjectName("p1_kg_unit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.p1_kg_unit)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.p2_kg_unit = QtWidgets.QLineEdit(self.tab_3)
        self.p2_kg_unit.setObjectName("p2_kg_unit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.p2_kg_unit)
        self.tabWidget.addTab(self.tab_3, "")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.source_id, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.unit_year)
        Dialog.setTabOrder(self.unit_year, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.hourly_profile)
        Dialog.setTabOrder(self.hourly_profile, self.daily_profile)
        Dialog.setTabOrder(self.daily_profile, self.monthly_profile)
        Dialog.setTabOrder(self.monthly_profile, self.co_kg_unit)
        Dialog.setTabOrder(self.co_kg_unit, self.hc_kg_unit)
        Dialog.setTabOrder(self.hc_kg_unit, self.nox_kg_unit)
        Dialog.setTabOrder(self.nox_kg_unit, self.sox_kg_unit)
        Dialog.setTabOrder(self.sox_kg_unit, self.pm10_kg_unit)
        Dialog.setTabOrder(self.pm10_kg_unit, self.p1_kg_unit)
        Dialog.setTabOrder(self.p1_kg_unit, self.p2_kg_unit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenALAQS - Area Sources"))
        self.instudy.setText(_translate("Dialog", "In Study"))
        self.label_47.setText(_translate("Dialog", "Source Name"))
        self.label.setText(_translate("Dialog", "Units per Year"))
        self.heightMLabel.setText(_translate("Dialog", "Height [m]"))
        self.heatFluxMwLabel.setText(_translate("Dialog", "Heat Flux [Mw]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Parameters"))
        self.label_9.setText(_translate("Dialog", "Hourly"))
        self.label_10.setText(_translate("Dialog", "Daily"))
        self.label_11.setText(_translate("Dialog", "Monthly"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Profiles"))
        self.label_13.setText(_translate("Dialog", "CO [kg/unit]"))
        self.label_14.setText(_translate("Dialog", "HC [kg/unit]"))
        self.label_15.setText(_translate("Dialog", "NOx [kg/unit]"))
        self.label_16.setText(_translate("Dialog", "SOx [kg/unit]"))
        self.label_17.setText(_translate("Dialog", "PM10 [kg/unit]"))
        self.label_18.setText(_translate("Dialog", "P1 [kg/unit]"))
        self.label_19.setText(_translate("Dialog", "P2 [kg/unit]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Emissions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
