# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_parkings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 383)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.instudy = QtWidgets.QCheckBox(Dialog)
        self.instudy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.instudy.setChecked(True)
        self.instudy.setObjectName("instudy")
        self.horizontalLayout.addWidget(self.instudy)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setObjectName("label_47")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.parking_id = QtWidgets.QLineEdit(Dialog)
        self.parking_id.setObjectName("parking_id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.parking_id)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.vehicle_year = QtWidgets.QLineEdit(self.tab)
        self.vehicle_year.setObjectName("vehicle_year")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vehicle_year)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.height = QtWidgets.QLineEdit(self.tab)
        self.height.setObjectName("height")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.height)
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.speed = QtWidgets.QLineEdit(self.tab)
        self.speed.setObjectName("speed")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.speed)
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.distance = QtWidgets.QLineEdit(self.tab)
        self.distance.setObjectName("distance")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.distance)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.idle_time = QtWidgets.QLineEdit(self.tab)
        self.idle_time.setObjectName("idle_time")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.idle_time)
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.park_time = QtWidgets.QLineEdit(self.tab)
        self.park_time.setObjectName("park_time")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.park_time)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.hour_profile = QtWidgets.QComboBox(self.tab_2)
        self.hour_profile.setObjectName("hour_profile")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hour_profile)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.daily_profile = QtWidgets.QComboBox(self.tab_2)
        self.daily_profile.setObjectName("daily_profile")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.daily_profile)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.month_profile = QtWidgets.QComboBox(self.tab_2)
        self.month_profile.setObjectName("month_profile")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.month_profile)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.co_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.co_gm_vh.setObjectName("co_gm_vh")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.co_gm_vh)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.hc_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.hc_gm_vh.setObjectName("hc_gm_vh")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hc_gm_vh)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.nox_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.nox_gm_vh.setObjectName("nox_gm_vh")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nox_gm_vh)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sox_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.sox_gm_vh.setObjectName("sox_gm_vh")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sox_gm_vh)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.pm10_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.pm10_gm_vh.setObjectName("pm10_gm_vh")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pm10_gm_vh)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.p1_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.p1_gm_vh.setObjectName("p1_gm_vh")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.p1_gm_vh)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.p2_gm_vh = QtWidgets.QLineEdit(self.tab_3)
        self.p2_gm_vh.setObjectName("p2_gm_vh")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.p2_gm_vh)
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.method = QtWidgets.QLineEdit(self.tab_3)
        self.method.setObjectName("method")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.method)
        self.button_recalculate = QtWidgets.QPushButton(self.tab_3)
        self.button_recalculate.setObjectName("button_recalculate")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.button_recalculate)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.tab_4)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.vehicle_light = QtWidgets.QLineEdit(self.tab_4)
        self.vehicle_light.setObjectName("vehicle_light")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vehicle_light)
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.vehicle_medium = QtWidgets.QLineEdit(self.tab_4)
        self.vehicle_medium.setObjectName("vehicle_medium")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vehicle_medium)
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.vehicle_heavy = QtWidgets.QLineEdit(self.tab_4)
        self.vehicle_heavy.setObjectName("vehicle_heavy")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vehicle_heavy)
        self.tabWidget.addTab(self.tab_4, "")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.parking_id, self.instudy)
        Dialog.setTabOrder(self.instudy, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.vehicle_year)
        Dialog.setTabOrder(self.vehicle_year, self.height)
        Dialog.setTabOrder(self.height, self.speed)
        Dialog.setTabOrder(self.speed, self.distance)
        Dialog.setTabOrder(self.distance, self.idle_time)
        Dialog.setTabOrder(self.idle_time, self.park_time)
        Dialog.setTabOrder(self.park_time, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.hour_profile)
        Dialog.setTabOrder(self.hour_profile, self.daily_profile)
        Dialog.setTabOrder(self.daily_profile, self.month_profile)
        Dialog.setTabOrder(self.month_profile, self.co_gm_vh)
        Dialog.setTabOrder(self.co_gm_vh, self.hc_gm_vh)
        Dialog.setTabOrder(self.hc_gm_vh, self.nox_gm_vh)
        Dialog.setTabOrder(self.nox_gm_vh, self.sox_gm_vh)
        Dialog.setTabOrder(self.sox_gm_vh, self.pm10_gm_vh)
        Dialog.setTabOrder(self.pm10_gm_vh, self.p1_gm_vh)
        Dialog.setTabOrder(self.p1_gm_vh, self.p2_gm_vh)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenALAQS - Parking"))
        self.instudy.setText(_translate("Dialog", "In Study"))
        self.label_47.setText(_translate("Dialog", "Source Name"))
        self.label.setText(_translate("Dialog", "Number per Year"))
        self.label_2.setText(_translate("Dialog", "Height [m]"))
        self.label_24.setText(_translate("Dialog", "Speed [km/h]"))
        self.label_33.setText(_translate("Dialog", "Travel Distance [m]"))
        self.label_35.setText(_translate("Dialog", "Idle Time [min]"))
        self.label_37.setText(_translate("Dialog", "Avg. Park Time [min]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Parameters"))
        self.label_9.setText(_translate("Dialog", "Hourly"))
        self.label_10.setText(_translate("Dialog", "Daily"))
        self.label_11.setText(_translate("Dialog", "Monthly"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Profiles"))
        self.label_13.setText(_translate("Dialog", "CO [g/vehicle]"))
        self.label_14.setText(_translate("Dialog", "HC [g/vehicle]"))
        self.label_15.setText(_translate("Dialog", "NOx [g/vehicle]"))
        self.label_16.setText(_translate("Dialog", "SOx [g/vehicle]"))
        self.label_17.setText(_translate("Dialog", "PM10 [g/vehicle]"))
        self.label_18.setText(_translate("Dialog", "P1 [g/vehicle]"))
        self.label_19.setText(_translate("Dialog", "P2 [g/vehicle]"))
        self.label_41.setText(_translate("Dialog", "Method"))
        self.method.setText(_translate("Dialog", "ALAQS"))
        self.button_recalculate.setText(_translate("Dialog", "Recalculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Emissions"))
        self.label_4.setText(_translate("Dialog", "PC [%]"))
        self.label_39.setText(_translate("Dialog", "LDV [%]"))
        self.label_40.setText(_translate("Dialog", "HDV [%]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Fleet Mix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
