# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_runways.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunwayDialog(object):
    def setupUi(self, RunwayDialog):
        RunwayDialog.setObjectName("RunwayDialog")
        RunwayDialog.resize(431, 254)
        self.gridLayout = QtWidgets.QGridLayout(RunwayDialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(RunwayDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.first_runway_number = QtWidgets.QComboBox(RunwayDialog)
        self.first_runway_number.setObjectName("first_runway_number")
        self.horizontalLayout.addWidget(self.first_runway_number)
        self.first_runway_letter = QtWidgets.QComboBox(RunwayDialog)
        self.first_runway_letter.setObjectName("first_runway_letter")
        self.horizontalLayout.addWidget(self.first_runway_letter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(RunwayDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.second_runway_number = QtWidgets.QComboBox(RunwayDialog)
        self.second_runway_number.setObjectName("second_runway_number")
        self.horizontalLayout_2.addWidget(self.second_runway_number)
        self.second_runway_letter = QtWidgets.QComboBox(RunwayDialog)
        self.second_runway_letter.setObjectName("second_runway_letter")
        self.horizontalLayout_2.addWidget(self.second_runway_letter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(RunwayDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.runway_id = QtWidgets.QLineEdit(RunwayDialog)
        self.runway_id.setObjectName("runway_id")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.runway_id)
        self.label_5 = QtWidgets.QLabel(RunwayDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.capacity = QtWidgets.QLineEdit(RunwayDialog)
        self.capacity.setObjectName("capacity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.capacity)
        self.label_2 = QtWidgets.QLabel(RunwayDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.touchdown = QtWidgets.QLineEdit(RunwayDialog)
        self.touchdown.setObjectName("touchdown")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.touchdown)
        self.label_3 = QtWidgets.QLabel(RunwayDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.max_queue_speed = QtWidgets.QLineEdit(RunwayDialog)
        self.max_queue_speed.setObjectName("max_queue_speed")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.max_queue_speed)
        self.label_4 = QtWidgets.QLabel(RunwayDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.peak_queue_time = QtWidgets.QLineEdit(RunwayDialog)
        self.peak_queue_time.setObjectName("peak_queue_time")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.peak_queue_time)
        self.buttonBox = QtWidgets.QDialogButtonBox(RunwayDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.instudy = QtWidgets.QCheckBox(RunwayDialog)
        self.instudy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.instudy.setChecked(True)
        self.instudy.setObjectName("instudy")
        self.horizontalLayout_3.addWidget(self.instudy)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(RunwayDialog)
        self.buttonBox.accepted.connect(RunwayDialog.accept)
        self.buttonBox.rejected.connect(RunwayDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RunwayDialog)
        RunwayDialog.setTabOrder(self.first_runway_number, self.first_runway_letter)
        RunwayDialog.setTabOrder(self.first_runway_letter, self.second_runway_number)
        RunwayDialog.setTabOrder(self.second_runway_number, self.second_runway_letter)
        RunwayDialog.setTabOrder(self.second_runway_letter, self.runway_id)
        RunwayDialog.setTabOrder(self.runway_id, self.capacity)
        RunwayDialog.setTabOrder(self.capacity, self.touchdown)
        RunwayDialog.setTabOrder(self.touchdown, self.max_queue_speed)
        RunwayDialog.setTabOrder(self.max_queue_speed, self.peak_queue_time)

    def retranslateUi(self, RunwayDialog):
        _translate = QtCore.QCoreApplication.translate
        RunwayDialog.setWindowTitle(_translate("RunwayDialog", "Runway Editor"))
        self.label.setText(_translate("RunwayDialog", "Runway 1"))
        self.label_6.setText(_translate("RunwayDialog", "Runway 2"))
        self.label_7.setText(_translate("RunwayDialog", "Runway Name"))
        self.label_5.setText(_translate("RunwayDialog", "Capacity (departures/h)"))
        self.capacity.setToolTip(_translate("RunwayDialog", "Enter the hourly capacity as number of departures per hour"))
        self.label_2.setText(_translate("RunwayDialog", "Touchdown Offset (m)"))
        self.touchdown.setToolTip(_translate("RunwayDialog", "Enter the distance between the runway end and the point of touchdown"))
        self.label_3.setText(_translate("RunwayDialog", "Max Queue Speed (km/h)"))
        self.max_queue_speed.setToolTip(_translate("RunwayDialog", "Enter the speed that the aircraft travels when queuing"))
        self.label_4.setText(_translate("RunwayDialog", "Peak Queue Time (mins)"))
        self.peak_queue_time.setToolTip(_translate("RunwayDialog", "Enter the time spent queuing to use this runway"))
        self.instudy.setText(_translate("RunwayDialog", "In Study"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RunwayDialog = QtWidgets.QDialog()
    ui = Ui_RunwayDialog()
    ui.setupUi(RunwayDialog)
    RunwayDialog.show()
    sys.exit(app.exec_())
