# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_roadways.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(353, 473)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(-1, 0, 0, -1)
        self.formLayout_7.setObjectName("formLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.instudy = QtWidgets.QCheckBox(Dialog)
        self.instudy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.instudy.setChecked(True)
        self.instudy.setObjectName("instudy")
        self.horizontalLayout_10.addWidget(self.instudy)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.roadway_id = QtWidgets.QLineEdit(Dialog)
        self.roadway_id.setObjectName("roadway_id")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roadway_id)
        self.verticalLayout.addLayout(self.formLayout_7)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setAutoFillBackground(False)
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.vehicle_year = QtWidgets.QLineEdit(self.tab)
        self.vehicle_year.setObjectName("vehicle_year")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vehicle_year)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.height = QtWidgets.QLineEdit(self.tab)
        self.height.setObjectName("height")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.height)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.hour_profile = QtWidgets.QComboBox(self.tab_2)
        self.hour_profile.setObjectName("hour_profile")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hour_profile)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.daily_profile = QtWidgets.QComboBox(self.tab_2)
        self.daily_profile.setObjectName("daily_profile")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.daily_profile)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.month_profile = QtWidgets.QComboBox(self.tab_2)
        self.month_profile.setObjectName("month_profile")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.month_profile)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName("tab_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.co_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.co_gm_km.setObjectName("co_gm_km")
        self.horizontalLayout_2.addWidget(self.co_gm_km)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hc_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.hc_gm_km.setObjectName("hc_gm_km")
        self.horizontalLayout_3.addWidget(self.hc_gm_km)
        self.formLayout_6.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nox_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.nox_gm_km.setObjectName("nox_gm_km")
        self.horizontalLayout_4.addWidget(self.nox_gm_km)
        self.formLayout_6.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pm10_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.pm10_gm_km.setObjectName("pm10_gm_km")
        self.horizontalLayout_6.addWidget(self.pm10_gm_km)
        self.formLayout_6.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.method = QtWidgets.QLineEdit(self.tab_3)
        self.method.setObjectName("method")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.method)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.button_recalculate = QtWidgets.QPushButton(self.tab_3)
        self.button_recalculate.setObjectName("button_recalculate")
        self.horizontalLayout_9.addWidget(self.button_recalculate)
        self.formLayout_6.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sox_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.sox_gm_km.setObjectName("sox_gm_km")
        self.horizontalLayout_5.addWidget(self.sox_gm_km)
        self.formLayout_6.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.p1_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.p1_gm_km.setObjectName("p1_gm_km")
        self.horizontalLayout_7.addWidget(self.p1_gm_km)
        self.formLayout_6.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.p2_gm_km = QtWidgets.QLineEdit(self.tab_3)
        self.p2_gm_km.setObjectName("p2_gm_km")
        self.horizontalLayout_8.addWidget(self.p2_gm_km)
        self.formLayout_6.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.tab_4)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.vehicle_light = QtWidgets.QLineEdit(self.tab_4)
        self.vehicle_light.setObjectName("vehicle_light")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vehicle_light)
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.vehicle_medium = QtWidgets.QLineEdit(self.tab_4)
        self.vehicle_medium.setObjectName("vehicle_medium")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vehicle_medium)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.vehicle_heavy = QtWidgets.QLineEdit(self.tab_4)
        self.vehicle_heavy.setObjectName("vehicle_heavy")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vehicle_heavy)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.speed = QtWidgets.QLineEdit(Dialog)
        self.speed.setText("")
        self.speed.setObjectName("speed")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speed)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.scenario = QtWidgets.QComboBox(Dialog)
        self.scenario.setObjectName("scenario")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scenario)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buttonBox, self.hc_gm_km)
        Dialog.setTabOrder(self.hc_gm_km, self.p2_gm_km)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open ALAQS - Roadways"))
        self.instudy.setText(_translate("Dialog", "In Study"))
        self.label_2.setText(_translate("Dialog", "Roadway Name"))
        self.label.setText(_translate("Dialog", "Movements per Year"))
        self.label_3.setText(_translate("Dialog", "Height [m]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Parameters"))
        self.label_10.setText(_translate("Dialog", "Hourly"))
        self.label_11.setText(_translate("Dialog", "Daily"))
        self.label_12.setText(_translate("Dialog", "Hourly"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Profiles"))
        self.label_14.setText(_translate("Dialog", "HC [g/km]"))
        self.label_15.setText(_translate("Dialog", "NOx [g/km]"))
        self.label_33.setText(_translate("Dialog", "Method"))
        self.method.setText(_translate("Dialog", "ALAQS"))
        self.button_recalculate.setText(_translate("Dialog", "Recalculate"))
        self.label_16.setText(_translate("Dialog", "SOx [g/km]"))
        self.label_17.setText(_translate("Dialog", "PM10 [g/km]"))
        self.label_18.setText(_translate("Dialog", "P1 [g/km]"))
        self.label_19.setText(_translate("Dialog", "P2 [g/km]"))
        self.label_13.setText(_translate("Dialog", "CO [g/km]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Emissions"))
        self.label_22.setText(_translate("Dialog", "PC [%]"))
        self.label_23.setText(_translate("Dialog", "LDV [%]"))
        self.label_24.setText(_translate("Dialog", "HDV [%]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Fleet Mix"))
        self.label_20.setText(_translate("Dialog", "Speed (km/h)"))
        self.label_21.setText(_translate("Dialog", "Scenario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
