# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_emissions_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.PyQt.QtWidgets import QSizePolicy


class Ui_EmissionsDialog(object):
    def setupUi(self, EmissionsDialog):
        EmissionsDialog.setObjectName("EmissionsDialog")
        EmissionsDialog.resize(820, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/icons/calculator.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        EmissionsDialog.setWindowIcon(icon)
        EmissionsDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(EmissionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(EmissionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetMovements = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tableWidgetMovements.sizePolicy().hasHeightForWidth()
        )
        self.tableWidgetMovements.setSizePolicy(sizePolicy)
        self.tableWidgetMovements.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.tableWidgetMovements.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.tableWidgetMovements.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows
        )
        self.tableWidgetMovements.setObjectName("tableWidgetMovements")
        self.tableWidgetMovements.setColumnCount(0)
        self.tableWidgetMovements.setRowCount(0)
        self.tableWidgetMovements.horizontalHeader().setVisible(True)
        self.tableWidgetMovements.verticalHeader().setVisible(False)
        self.tableWidgetMovements.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_2.addWidget(self.tableWidgetMovements)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCalculate_Emissions = QtWidgets.QPushButton(EmissionsDialog)
        self.pushButtonCalculate_Emissions.setObjectName(
            "pushButtonCalculate_Emissions"
        )
        self.horizontalLayout.addWidget(self.pushButtonCalculate_Emissions)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(EmissionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidgetOutput = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tableWidgetOutput.sizePolicy().hasHeightForWidth()
        )
        self.tableWidgetOutput.setSizePolicy(sizePolicy)
        self.tableWidgetOutput.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tableWidgetOutput.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.tableWidgetOutput.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows
        )
        self.tableWidgetOutput.setObjectName("tableWidgetOutput")
        self.tableWidgetOutput.setColumnCount(0)
        self.tableWidgetOutput.setRowCount(0)
        self.tableWidgetOutput.horizontalHeader().setVisible(True)
        self.tableWidgetOutput.verticalHeader().setVisible(False)
        self.tableWidgetOutput.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_3.addWidget(self.tableWidgetOutput)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonExport_Table = QtWidgets.QPushButton(EmissionsDialog)
        self.pushButtonExport_Table.setEnabled(False)
        self.pushButtonExport_Table.setObjectName("pushButtonExport_Table")
        self.horizontalLayout_2.addWidget(self.pushButtonExport_Table)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(EmissionsDialog)
        QtCore.QMetaObject.connectSlotsByName(EmissionsDialog)

    def retranslateUi(self, EmissionsDialog):
        _translate = QtCore.QCoreApplication.translate
        EmissionsDialog.setWindowTitle(
            _translate("EmissionsDialog", "Emissions Calculator")
        )
        self.groupBox.setTitle(_translate("EmissionsDialog", "GSE List by Movement"))
        self.pushButtonCalculate_Emissions.setText(
            _translate("EmissionsDialog", "Calculate Emissions")
        )
        self.groupBox_2.setTitle(_translate("EmissionsDialog", "Output Emissions"))
        self.pushButtonExport_Table.setText(
            _translate("EmissionsDialog", "Export table to CSV")
        )
