# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_profiles_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormProfiles(object):
    def setupUi(self, FormProfiles):
        FormProfiles.setObjectName("FormProfiles")
        FormProfiles.resize(310, 440)
        self.pushButtonCancel = QtWidgets.QPushButton(FormProfiles)
        self.pushButtonCancel.setGeometry(QtCore.QRect(240, 410, 61, 23))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.tabWidget = QtWidgets.QTabWidget(FormProfiles)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 291, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBoxHourlyName = QtWidgets.QComboBox(self.tab)
        self.comboBoxHourlyName.setGeometry(QtCore.QRect(90, 20, 171, 22))
        self.comboBoxHourlyName.setObjectName("comboBoxHourlyName")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 61, 21, 20))
        self.label_4.setObjectName("label_4")
        self.lineEditHourly00 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly00.setGeometry(QtCore.QRect(30, 60, 61, 21))
        self.lineEditHourly00.setText("")
        self.lineEditHourly00.setObjectName("lineEditHourly00")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 91, 21, 20))
        self.label_5.setObjectName("label_5")
        self.lineEditHourly01 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly01.setGeometry(QtCore.QRect(30, 90, 61, 21))
        self.lineEditHourly01.setText("")
        self.lineEditHourly01.setObjectName("lineEditHourly01")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 121, 21, 20))
        self.label_6.setObjectName("label_6")
        self.lineEditHourly02 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly02.setGeometry(QtCore.QRect(30, 120, 61, 21))
        self.lineEditHourly02.setText("")
        self.lineEditHourly02.setObjectName("lineEditHourly02")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 151, 21, 20))
        self.label_7.setObjectName("label_7")
        self.lineEditHourly03 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly03.setGeometry(QtCore.QRect(30, 150, 61, 21))
        self.lineEditHourly03.setText("")
        self.lineEditHourly03.setObjectName("lineEditHourly03")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 181, 21, 20))
        self.label_8.setObjectName("label_8")
        self.lineEditHourly04 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly04.setGeometry(QtCore.QRect(30, 180, 61, 21))
        self.lineEditHourly04.setText("")
        self.lineEditHourly04.setObjectName("lineEditHourly04")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 211, 21, 20))
        self.label_9.setObjectName("label_9")
        self.lineEditHourly05 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly05.setGeometry(QtCore.QRect(30, 210, 61, 21))
        self.lineEditHourly05.setText("")
        self.lineEditHourly05.setObjectName("lineEditHourly05")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 241, 21, 20))
        self.label_10.setObjectName("label_10")
        self.lineEditHourly06 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly06.setGeometry(QtCore.QRect(30, 240, 61, 21))
        self.lineEditHourly06.setText("")
        self.lineEditHourly06.setObjectName("lineEditHourly06")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 271, 21, 20))
        self.label_11.setObjectName("label_11")
        self.lineEditHourly07 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly07.setGeometry(QtCore.QRect(30, 270, 61, 21))
        self.lineEditHourly07.setText("")
        self.lineEditHourly07.setObjectName("lineEditHourly07")
        self.lineEditHourly11 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly11.setGeometry(QtCore.QRect(120, 150, 61, 21))
        self.lineEditHourly11.setText("")
        self.lineEditHourly11.setObjectName("lineEditHourly11")
        self.lineEditHourly14 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly14.setGeometry(QtCore.QRect(120, 240, 61, 21))
        self.lineEditHourly14.setText("")
        self.lineEditHourly14.setObjectName("lineEditHourly14")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(100, 61, 21, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(100, 91, 21, 20))
        self.label_13.setObjectName("label_13")
        self.lineEditHourly12 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly12.setGeometry(QtCore.QRect(120, 180, 61, 21))
        self.lineEditHourly12.setText("")
        self.lineEditHourly12.setObjectName("lineEditHourly12")
        self.lineEditHourly13 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly13.setGeometry(QtCore.QRect(120, 210, 61, 21))
        self.lineEditHourly13.setText("")
        self.lineEditHourly13.setObjectName("lineEditHourly13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(100, 151, 21, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(100, 271, 21, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(100, 121, 21, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(100, 211, 21, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(100, 241, 21, 20))
        self.label_18.setObjectName("label_18")
        self.lineEditHourly08 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly08.setGeometry(QtCore.QRect(120, 60, 61, 21))
        self.lineEditHourly08.setText("")
        self.lineEditHourly08.setObjectName("lineEditHourly08")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(100, 181, 21, 20))
        self.label_19.setObjectName("label_19")
        self.lineEditHourly09 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly09.setGeometry(QtCore.QRect(120, 90, 61, 21))
        self.lineEditHourly09.setText("")
        self.lineEditHourly09.setObjectName("lineEditHourly09")
        self.lineEditHourly10 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly10.setGeometry(QtCore.QRect(120, 120, 61, 21))
        self.lineEditHourly10.setText("")
        self.lineEditHourly10.setObjectName("lineEditHourly10")
        self.lineEditHourly19 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly19.setGeometry(QtCore.QRect(210, 150, 61, 21))
        self.lineEditHourly19.setText("")
        self.lineEditHourly19.setObjectName("lineEditHourly19")
        self.lineEditHourly22 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly22.setGeometry(QtCore.QRect(210, 240, 61, 21))
        self.lineEditHourly22.setText("")
        self.lineEditHourly22.setObjectName("lineEditHourly22")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(190, 61, 21, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(190, 91, 21, 20))
        self.label_21.setObjectName("label_21")
        self.lineEditHourly20 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly20.setGeometry(QtCore.QRect(210, 180, 61, 21))
        self.lineEditHourly20.setText("")
        self.lineEditHourly20.setObjectName("lineEditHourly20")
        self.lineEditHourly21 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly21.setGeometry(QtCore.QRect(210, 210, 61, 21))
        self.lineEditHourly21.setText("")
        self.lineEditHourly21.setObjectName("lineEditHourly21")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(190, 151, 21, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(190, 271, 21, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(190, 121, 21, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(190, 211, 21, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(190, 241, 21, 20))
        self.label_26.setObjectName("label_26")
        self.lineEditHourly16 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly16.setGeometry(QtCore.QRect(210, 60, 61, 21))
        self.lineEditHourly16.setText("")
        self.lineEditHourly16.setObjectName("lineEditHourly16")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(190, 181, 21, 20))
        self.label_27.setObjectName("label_27")
        self.lineEditHourly17 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly17.setGeometry(QtCore.QRect(210, 90, 61, 21))
        self.lineEditHourly17.setText("")
        self.lineEditHourly17.setObjectName("lineEditHourly17")
        self.lineEditHourly18 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly18.setGeometry(QtCore.QRect(210, 120, 61, 21))
        self.lineEditHourly18.setText("")
        self.lineEditHourly18.setObjectName("lineEditHourly18")
        self.lineEditHourly15 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly15.setGeometry(QtCore.QRect(120, 270, 61, 21))
        self.lineEditHourly15.setText("")
        self.lineEditHourly15.setObjectName("lineEditHourly15")
        self.lineEditHourly23 = QtWidgets.QLineEdit(self.tab)
        self.lineEditHourly23.setGeometry(QtCore.QRect(210, 270, 61, 21))
        self.lineEditHourly23.setText("")
        self.lineEditHourly23.setObjectName("lineEditHourly23")
        self.pushButtonHourlyClear = QtWidgets.QPushButton(self.tab)
        self.pushButtonHourlyClear.setGeometry(QtCore.QRect(220, 320, 61, 23))
        self.pushButtonHourlyClear.setObjectName("pushButtonHourlyClear")
        self.pushButtonHourlyDelete = QtWidgets.QPushButton(self.tab)
        self.pushButtonHourlyDelete.setGeometry(QtCore.QRect(10, 320, 61, 23))
        self.pushButtonHourlyDelete.setObjectName("pushButtonHourlyDelete")
        self.pushButtonHourlyNew = QtWidgets.QPushButton(self.tab)
        self.pushButtonHourlyNew.setGeometry(QtCore.QRect(80, 320, 61, 23))
        self.pushButtonHourlyNew.setObjectName("pushButtonHourlyNew")
        self.pushButtonHourlySave = QtWidgets.QPushButton(self.tab)
        self.pushButtonHourlySave.setGeometry(QtCore.QRect(150, 320, 61, 23))
        self.pushButtonHourlySave.setObjectName("pushButtonHourlySave")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBoxDailyName = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxDailyName.setGeometry(QtCore.QRect(90, 20, 171, 22))
        self.comboBoxDailyName.setObjectName("comboBoxDailyName")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label_28.setObjectName("label_28")
        self.lineEditDailyMon = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailyMon.setGeometry(QtCore.QRect(110, 60, 121, 21))
        self.lineEditDailyMon.setObjectName("lineEditDailyMon")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(30, 90, 71, 21))
        self.label_29.setObjectName("label_29")
        self.lineEditDailyTues = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailyTues.setGeometry(QtCore.QRect(110, 90, 121, 21))
        self.lineEditDailyTues.setObjectName("lineEditDailyTues")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(30, 120, 71, 21))
        self.label_30.setObjectName("label_30")
        self.lineEditDailyWed = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailyWed.setGeometry(QtCore.QRect(110, 120, 121, 21))
        self.lineEditDailyWed.setObjectName("lineEditDailyWed")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(30, 150, 71, 21))
        self.label_31.setObjectName("label_31")
        self.lineEditDailyThurs = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailyThurs.setGeometry(QtCore.QRect(110, 150, 121, 21))
        self.lineEditDailyThurs.setObjectName("lineEditDailyThurs")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(30, 180, 71, 21))
        self.label_32.setObjectName("label_32")
        self.lineEditDailyFri = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailyFri.setGeometry(QtCore.QRect(110, 180, 121, 21))
        self.lineEditDailyFri.setObjectName("lineEditDailyFri")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(30, 210, 71, 21))
        self.label_33.setObjectName("label_33")
        self.lineEditDailySat = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailySat.setGeometry(QtCore.QRect(110, 210, 121, 21))
        self.lineEditDailySat.setObjectName("lineEditDailySat")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(30, 240, 71, 21))
        self.label_34.setObjectName("label_34")
        self.lineEditDailySun = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditDailySun.setGeometry(QtCore.QRect(110, 240, 121, 21))
        self.lineEditDailySun.setObjectName("lineEditDailySun")
        self.pushButtonDailyClear = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDailyClear.setGeometry(QtCore.QRect(220, 320, 61, 23))
        self.pushButtonDailyClear.setObjectName("pushButtonDailyClear")
        self.pushButtonDailyDelete = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDailyDelete.setGeometry(QtCore.QRect(10, 320, 61, 23))
        self.pushButtonDailyDelete.setObjectName("pushButtonDailyDelete")
        self.pushButtonDailyNew = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDailyNew.setGeometry(QtCore.QRect(80, 320, 61, 23))
        self.pushButtonDailyNew.setObjectName("pushButtonDailyNew")
        self.pushButtonDailySave = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDailySave.setGeometry(QtCore.QRect(150, 320, 61, 23))
        self.pushButtonDailySave.setObjectName("pushButtonDailySave")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBoxMonthlyName = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxMonthlyName.setGeometry(QtCore.QRect(90, 20, 171, 22))
        self.comboBoxMonthlyName.setObjectName("comboBoxMonthlyName")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_69 = QtWidgets.QLabel(self.tab_3)
        self.label_69.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.label_69.setObjectName("label_69")
        self.lineEditMonthlyJan = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyJan.setGeometry(QtCore.QRect(60, 60, 71, 21))
        self.lineEditMonthlyJan.setObjectName("lineEditMonthlyJan")
        self.label_70 = QtWidgets.QLabel(self.tab_3)
        self.label_70.setGeometry(QtCore.QRect(140, 60, 51, 21))
        self.label_70.setObjectName("label_70")
        self.lineEditMonthlyJul = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyJul.setGeometry(QtCore.QRect(200, 60, 71, 21))
        self.lineEditMonthlyJul.setObjectName("lineEditMonthlyJul")
        self.label_71 = QtWidgets.QLabel(self.tab_3)
        self.label_71.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.tab_3)
        self.label_72.setGeometry(QtCore.QRect(140, 90, 51, 21))
        self.label_72.setObjectName("label_72")
        self.lineEditMonthlyFeb = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyFeb.setGeometry(QtCore.QRect(60, 90, 71, 21))
        self.lineEditMonthlyFeb.setObjectName("lineEditMonthlyFeb")
        self.lineEditMonthlyAug = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyAug.setGeometry(QtCore.QRect(200, 90, 71, 21))
        self.lineEditMonthlyAug.setObjectName("lineEditMonthlyAug")
        self.label_73 = QtWidgets.QLabel(self.tab_3)
        self.label_73.setGeometry(QtCore.QRect(10, 120, 51, 21))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_3)
        self.label_74.setGeometry(QtCore.QRect(140, 120, 51, 21))
        self.label_74.setObjectName("label_74")
        self.lineEditMonthlyMar = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyMar.setGeometry(QtCore.QRect(60, 120, 71, 21))
        self.lineEditMonthlyMar.setObjectName("lineEditMonthlyMar")
        self.lineEditMonthlySep = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlySep.setGeometry(QtCore.QRect(200, 120, 71, 21))
        self.lineEditMonthlySep.setObjectName("lineEditMonthlySep")
        self.label_75 = QtWidgets.QLabel(self.tab_3)
        self.label_75.setGeometry(QtCore.QRect(10, 150, 51, 21))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.tab_3)
        self.label_76.setGeometry(QtCore.QRect(140, 150, 51, 21))
        self.label_76.setObjectName("label_76")
        self.lineEditMonthlyApr = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyApr.setGeometry(QtCore.QRect(60, 150, 71, 21))
        self.lineEditMonthlyApr.setObjectName("lineEditMonthlyApr")
        self.lineEditMonthlyOct = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyOct.setGeometry(QtCore.QRect(200, 150, 71, 21))
        self.lineEditMonthlyOct.setObjectName("lineEditMonthlyOct")
        self.label_77 = QtWidgets.QLabel(self.tab_3)
        self.label_77.setGeometry(QtCore.QRect(10, 180, 51, 21))
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_3)
        self.label_78.setGeometry(QtCore.QRect(140, 180, 51, 21))
        self.label_78.setObjectName("label_78")
        self.lineEditMonthlyMay = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyMay.setGeometry(QtCore.QRect(60, 180, 71, 21))
        self.lineEditMonthlyMay.setObjectName("lineEditMonthlyMay")
        self.lineEditMonthlyNov = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyNov.setGeometry(QtCore.QRect(200, 180, 71, 21))
        self.lineEditMonthlyNov.setObjectName("lineEditMonthlyNov")
        self.label_79 = QtWidgets.QLabel(self.tab_3)
        self.label_79.setGeometry(QtCore.QRect(10, 210, 51, 21))
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab_3)
        self.label_80.setGeometry(QtCore.QRect(140, 210, 51, 21))
        self.label_80.setObjectName("label_80")
        self.lineEditMonthlyJun = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyJun.setGeometry(QtCore.QRect(60, 210, 71, 21))
        self.lineEditMonthlyJun.setObjectName("lineEditMonthlyJun")
        self.lineEditMonthlyDec = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditMonthlyDec.setGeometry(QtCore.QRect(200, 210, 71, 21))
        self.lineEditMonthlyDec.setObjectName("lineEditMonthlyDec")
        self.pushButtonMonthlyClear = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonMonthlyClear.setGeometry(QtCore.QRect(220, 320, 61, 23))
        self.pushButtonMonthlyClear.setObjectName("pushButtonMonthlyClear")
        self.pushButtonMonthlyNew = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonMonthlyNew.setGeometry(QtCore.QRect(80, 320, 61, 23))
        self.pushButtonMonthlyNew.setObjectName("pushButtonMonthlyNew")
        self.pushButtonMonthlySave = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonMonthlySave.setGeometry(QtCore.QRect(150, 320, 61, 23))
        self.pushButtonMonthlySave.setObjectName("pushButtonMonthlySave")
        self.pushButtonMonthlyDelete = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonMonthlyDelete.setGeometry(QtCore.QRect(10, 320, 61, 23))
        self.pushButtonMonthlyDelete.setObjectName("pushButtonMonthlyDelete")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(FormProfiles)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormProfiles)
        FormProfiles.setTabOrder(self.tabWidget, self.comboBoxHourlyName)
        FormProfiles.setTabOrder(self.comboBoxHourlyName, self.lineEditHourly00)
        FormProfiles.setTabOrder(self.lineEditHourly00, self.lineEditHourly01)
        FormProfiles.setTabOrder(self.lineEditHourly01, self.lineEditHourly02)
        FormProfiles.setTabOrder(self.lineEditHourly02, self.lineEditHourly03)
        FormProfiles.setTabOrder(self.lineEditHourly03, self.lineEditHourly04)
        FormProfiles.setTabOrder(self.lineEditHourly04, self.lineEditHourly05)
        FormProfiles.setTabOrder(self.lineEditHourly05, self.lineEditHourly06)
        FormProfiles.setTabOrder(self.lineEditHourly06, self.lineEditHourly07)
        FormProfiles.setTabOrder(self.lineEditHourly07, self.lineEditHourly08)
        FormProfiles.setTabOrder(self.lineEditHourly08, self.lineEditHourly09)
        FormProfiles.setTabOrder(self.lineEditHourly09, self.lineEditHourly10)
        FormProfiles.setTabOrder(self.lineEditHourly10, self.lineEditHourly11)
        FormProfiles.setTabOrder(self.lineEditHourly11, self.lineEditHourly12)
        FormProfiles.setTabOrder(self.lineEditHourly12, self.lineEditHourly13)
        FormProfiles.setTabOrder(self.lineEditHourly13, self.lineEditHourly14)
        FormProfiles.setTabOrder(self.lineEditHourly14, self.lineEditHourly15)
        FormProfiles.setTabOrder(self.lineEditHourly15, self.lineEditHourly16)
        FormProfiles.setTabOrder(self.lineEditHourly16, self.lineEditHourly17)
        FormProfiles.setTabOrder(self.lineEditHourly17, self.lineEditHourly18)
        FormProfiles.setTabOrder(self.lineEditHourly18, self.lineEditHourly19)
        FormProfiles.setTabOrder(self.lineEditHourly19, self.lineEditHourly20)
        FormProfiles.setTabOrder(self.lineEditHourly20, self.lineEditHourly21)
        FormProfiles.setTabOrder(self.lineEditHourly21, self.lineEditHourly22)
        FormProfiles.setTabOrder(self.lineEditHourly22, self.lineEditHourly23)
        FormProfiles.setTabOrder(self.lineEditHourly23, self.pushButtonHourlyDelete)
        FormProfiles.setTabOrder(self.pushButtonHourlyDelete, self.pushButtonHourlyNew)
        FormProfiles.setTabOrder(self.pushButtonHourlyNew, self.pushButtonHourlySave)
        FormProfiles.setTabOrder(self.pushButtonHourlySave, self.pushButtonHourlyClear)
        FormProfiles.setTabOrder(self.pushButtonHourlyClear, self.pushButtonCancel)
        FormProfiles.setTabOrder(self.pushButtonCancel, self.comboBoxDailyName)
        FormProfiles.setTabOrder(self.comboBoxDailyName, self.lineEditDailyMon)
        FormProfiles.setTabOrder(self.lineEditDailyMon, self.lineEditDailyTues)
        FormProfiles.setTabOrder(self.lineEditDailyTues, self.lineEditDailyWed)
        FormProfiles.setTabOrder(self.lineEditDailyWed, self.lineEditDailyThurs)
        FormProfiles.setTabOrder(self.lineEditDailyThurs, self.lineEditDailyFri)
        FormProfiles.setTabOrder(self.lineEditDailyFri, self.lineEditDailySat)
        FormProfiles.setTabOrder(self.lineEditDailySat, self.lineEditDailySun)
        FormProfiles.setTabOrder(self.lineEditDailySun, self.comboBoxMonthlyName)
        FormProfiles.setTabOrder(self.comboBoxMonthlyName, self.lineEditMonthlyJan)
        FormProfiles.setTabOrder(self.lineEditMonthlyJan, self.lineEditMonthlyFeb)
        FormProfiles.setTabOrder(self.lineEditMonthlyFeb, self.lineEditMonthlyMar)
        FormProfiles.setTabOrder(self.lineEditMonthlyMar, self.lineEditMonthlyApr)
        FormProfiles.setTabOrder(self.lineEditMonthlyApr, self.lineEditMonthlyMay)
        FormProfiles.setTabOrder(self.lineEditMonthlyMay, self.lineEditMonthlyJun)
        FormProfiles.setTabOrder(self.lineEditMonthlyJun, self.lineEditMonthlyJul)
        FormProfiles.setTabOrder(self.lineEditMonthlyJul, self.lineEditMonthlyAug)
        FormProfiles.setTabOrder(self.lineEditMonthlyAug, self.lineEditMonthlySep)
        FormProfiles.setTabOrder(self.lineEditMonthlySep, self.lineEditMonthlyOct)
        FormProfiles.setTabOrder(self.lineEditMonthlyOct, self.lineEditMonthlyNov)
        FormProfiles.setTabOrder(self.lineEditMonthlyNov, self.lineEditMonthlyDec)
        FormProfiles.setTabOrder(self.lineEditMonthlyDec, self.pushButtonMonthlyDelete)
        FormProfiles.setTabOrder(self.pushButtonMonthlyDelete, self.pushButtonMonthlyNew)
        FormProfiles.setTabOrder(self.pushButtonMonthlyNew, self.pushButtonMonthlySave)
        FormProfiles.setTabOrder(self.pushButtonMonthlySave, self.pushButtonMonthlyClear)
        FormProfiles.setTabOrder(self.pushButtonMonthlyClear, self.pushButtonDailySave)
        FormProfiles.setTabOrder(self.pushButtonDailySave, self.pushButtonDailyDelete)
        FormProfiles.setTabOrder(self.pushButtonDailyDelete, self.pushButtonDailyClear)
        FormProfiles.setTabOrder(self.pushButtonDailyClear, self.pushButtonDailyNew)

    def retranslateUi(self, FormProfiles):
        _translate = QtCore.QCoreApplication.translate
        FormProfiles.setWindowTitle(_translate("FormProfiles", "Open ALAQS - Activity Profiles"))
        self.pushButtonCancel.setText(_translate("FormProfiles", "Finished"))
        self.label_3.setText(_translate("FormProfiles", "Profile:"))
        self.label_4.setText(_translate("FormProfiles", "00"))
        self.label_5.setText(_translate("FormProfiles", "01"))
        self.label_6.setText(_translate("FormProfiles", "02"))
        self.label_7.setText(_translate("FormProfiles", "03"))
        self.label_8.setText(_translate("FormProfiles", "04"))
        self.label_9.setText(_translate("FormProfiles", "05"))
        self.label_10.setText(_translate("FormProfiles", "06"))
        self.label_11.setText(_translate("FormProfiles", "07"))
        self.label_12.setText(_translate("FormProfiles", "08"))
        self.label_13.setText(_translate("FormProfiles", "09"))
        self.label_14.setText(_translate("FormProfiles", "11"))
        self.label_15.setText(_translate("FormProfiles", "15"))
        self.label_16.setText(_translate("FormProfiles", "10"))
        self.label_17.setText(_translate("FormProfiles", "13"))
        self.label_18.setText(_translate("FormProfiles", "14"))
        self.label_19.setText(_translate("FormProfiles", "12"))
        self.label_20.setText(_translate("FormProfiles", "16"))
        self.label_21.setText(_translate("FormProfiles", "17"))
        self.label_22.setText(_translate("FormProfiles", "19"))
        self.label_23.setText(_translate("FormProfiles", "23"))
        self.label_24.setText(_translate("FormProfiles", "18"))
        self.label_25.setText(_translate("FormProfiles", "21"))
        self.label_26.setText(_translate("FormProfiles", "22"))
        self.label_27.setText(_translate("FormProfiles", "20"))
        self.pushButtonHourlyClear.setText(_translate("FormProfiles", "Clear List"))
        self.pushButtonHourlyDelete.setText(_translate("FormProfiles", "Delete"))
        self.pushButtonHourlyNew.setText(_translate("FormProfiles", "New"))
        self.pushButtonHourlySave.setText(_translate("FormProfiles", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FormProfiles", "Hourly"))
        self.label_2.setText(_translate("FormProfiles", "Profile:"))
        self.label_28.setText(_translate("FormProfiles", "Monday"))
        self.label_29.setText(_translate("FormProfiles", "Tuesday"))
        self.label_30.setText(_translate("FormProfiles", "Wednesday"))
        self.label_31.setText(_translate("FormProfiles", "Thursday"))
        self.label_32.setText(_translate("FormProfiles", "Friday"))
        self.label_33.setText(_translate("FormProfiles", "Saturday"))
        self.label_34.setText(_translate("FormProfiles", "Sunday"))
        self.pushButtonDailyClear.setText(_translate("FormProfiles", "Clear List"))
        self.pushButtonDailyDelete.setText(_translate("FormProfiles", "Delete"))
        self.pushButtonDailyNew.setText(_translate("FormProfiles", "New"))
        self.pushButtonDailySave.setText(_translate("FormProfiles", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FormProfiles", "Daily"))
        self.label.setText(_translate("FormProfiles", "Profile:"))
        self.label_69.setText(_translate("FormProfiles", "January"))
        self.label_70.setText(_translate("FormProfiles", "July"))
        self.label_71.setText(_translate("FormProfiles", "February"))
        self.label_72.setText(_translate("FormProfiles", "August"))
        self.label_73.setText(_translate("FormProfiles", "March"))
        self.label_74.setText(_translate("FormProfiles", "September"))
        self.label_75.setText(_translate("FormProfiles", "April"))
        self.label_76.setText(_translate("FormProfiles", "October"))
        self.label_77.setText(_translate("FormProfiles", "May"))
        self.label_78.setText(_translate("FormProfiles", "November"))
        self.label_79.setText(_translate("FormProfiles", "June"))
        self.label_80.setText(_translate("FormProfiles", "December"))
        self.pushButtonMonthlyClear.setText(_translate("FormProfiles", "Clear List"))
        self.pushButtonMonthlyNew.setText(_translate("FormProfiles", "New"))
        self.pushButtonMonthlySave.setText(_translate("FormProfiles", "Save"))
        self.pushButtonMonthlyDelete.setText(_translate("FormProfiles", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("FormProfiles", "Monthly"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormProfiles = QtWidgets.QWidget()
    ui = Ui_FormProfiles()
    ui.setupUi(FormProfiles)
    FormProfiles.show()
    sys.exit(app.exec_())
