# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sst/Dropbox/WorkOn/Projects/OpenALAQS/code/open_alaqs/ui/ui_run_austal2000.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogRunAUSTAL2000(object):
    def setupUi(self, DialogRunAUSTAL2000):
        DialogRunAUSTAL2000.setObjectName("DialogRunAUSTAL2000")
        DialogRunAUSTAL2000.resize(641, 629)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogRunAUSTAL2000.sizePolicy().hasHeightForWidth())
        DialogRunAUSTAL2000.setSizePolicy(sizePolicy)
        DialogRunAUSTAL2000.setModal(True)
        self.line_2 = QtWidgets.QFrame(DialogRunAUSTAL2000)
        self.line_2.setGeometry(QtCore.QRect(20, 130, 591, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.RunA2K = QtWidgets.QPushButton(DialogRunAUSTAL2000)
        self.RunA2K.setGeometry(QtCore.QRect(257, 180, 131, 41))
        self.RunA2K.setObjectName("RunA2K")
        self.frame = QtWidgets.QFrame(DialogRunAUSTAL2000)
        self.frame.setGeometry(QtCore.QRect(10, 230, 621, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(DialogRunAUSTAL2000)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 591, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditFilename_a2k = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFilename_a2k.sizePolicy().hasHeightForWidth())
        self.lineEditFilename_a2k.setSizePolicy(sizePolicy)
        self.lineEditFilename_a2k.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditFilename_a2k.setAcceptDrops(False)
        self.lineEditFilename_a2k.setText("")
        self.lineEditFilename_a2k.setObjectName("lineEditFilename_a2k")
        self.gridLayout_2.addWidget(self.lineEditFilename_a2k, 1, 0, 1, 1)
        self.pushButtonBrowse_a2k = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonBrowse_a2k.setObjectName("pushButtonBrowse_a2k")
        self.gridLayout_2.addWidget(self.pushButtonBrowse_a2k, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditFilename_work_dir = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFilename_work_dir.sizePolicy().hasHeightForWidth())
        self.lineEditFilename_work_dir.setSizePolicy(sizePolicy)
        self.lineEditFilename_work_dir.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditFilename_work_dir.setText("")
        self.lineEditFilename_work_dir.setObjectName("lineEditFilename_work_dir")
        self.gridLayout_2.addWidget(self.lineEditFilename_work_dir, 3, 0, 1, 1)
        self.pushButtonBrowse_work_dir = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonBrowse_work_dir.setObjectName("pushButtonBrowse_work_dir")
        self.gridLayout_2.addWidget(self.pushButtonBrowse_work_dir, 3, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(DialogRunAUSTAL2000)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 140, 111, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_3.addWidget(self.radioButton, 0, 1, 2, 1)
        self.layoutWidget2 = QtWidgets.QWidget(DialogRunAUSTAL2000)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 235, 598, 381))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_query_results = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_query_results.setFont(font)
        self.label_query_results.setObjectName("label_query_results")
        self.gridLayout.addWidget(self.label_query_results, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_modules = QtWidgets.QLabel(self.layoutWidget2)
        self.label_modules.setObjectName("label_modules")
        self.gridLayout_9.addWidget(self.label_modules, 0, 0, 1, 1)
        self.Configuration_toolBox = QtWidgets.QToolBox(self.layoutWidget2)
        self.Configuration_toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Configuration_toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Configuration_toolBox.setObjectName("Configuration_toolBox")
        self.output_modules_page = QtWidgets.QWidget()
        self.output_modules_page.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.output_modules_page.setObjectName("output_modules_page")
        self.output_modules_tab_widget = QtWidgets.QTabWidget(self.output_modules_page)
        self.output_modules_tab_widget.setGeometry(QtCore.QRect(20, 0, 431, 151))
        self.output_modules_tab_widget.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setKerning(True)
        self.output_modules_tab_widget.setFont(font)
        self.output_modules_tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.output_modules_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.output_modules_tab_widget.setDocumentMode(True)
        self.output_modules_tab_widget.setMovable(False)
        self.output_modules_tab_widget.setObjectName("output_modules_tab_widget")
        self.Configuration_toolBox.addItem(self.output_modules_page, "")
        self.visualisation_modules_page = QtWidgets.QWidget()
        self.visualisation_modules_page.setGeometry(QtCore.QRect(0, 0, 523, 172))
        self.visualisation_modules_page.setObjectName("visualisation_modules_page")
        self.visualization_modules_tab_widget = QtWidgets.QTabWidget(self.visualisation_modules_page)
        self.visualization_modules_tab_widget.setGeometry(QtCore.QRect(12, 0, 451, 161))
        self.visualization_modules_tab_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.visualization_modules_tab_widget.setDocumentMode(True)
        self.visualization_modules_tab_widget.setObjectName("visualization_modules_tab_widget")
        self.Configuration_toolBox.addItem(self.visualisation_modules_page, "")
        self.gridLayout_9.addWidget(self.Configuration_toolBox, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.alaqs_output_file = QtWidgets.QLabel(self.layoutWidget2)
        self.alaqs_output_file.setObjectName("alaqs_output_file")
        self.gridLayout_7.addWidget(self.alaqs_output_file, 0, 0, 1, 1)
        self.lineEditFilename_alaqs = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFilename_alaqs.sizePolicy().hasHeightForWidth())
        self.lineEditFilename_alaqs.setSizePolicy(sizePolicy)
        self.lineEditFilename_alaqs.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditFilename_alaqs.setText("")
        self.lineEditFilename_alaqs.setObjectName("lineEditFilename_alaqs")
        self.gridLayout_7.addWidget(self.lineEditFilename_alaqs, 1, 0, 1, 1)
        self.pushButtonBrowse_alaqs = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButtonBrowse_alaqs.setObjectName("pushButtonBrowse_alaqs")
        self.gridLayout_7.addWidget(self.pushButtonBrowse_alaqs, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CancelButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout_6.addWidget(self.CancelButton, 0, 3, 1, 1)
        self.VisualiseResults = QtWidgets.QPushButton(self.layoutWidget2)
        self.VisualiseResults.setObjectName("VisualiseResults")
        self.gridLayout_6.addWidget(self.VisualiseResults, 0, 0, 1, 1)
        self.PlotTimeSeries = QtWidgets.QPushButton(self.layoutWidget2)
        self.PlotTimeSeries.setObjectName("PlotTimeSeries")
        self.gridLayout_6.addWidget(self.PlotTimeSeries, 0, 1, 1, 1)
        self.ResultsTable = QtWidgets.QPushButton(self.layoutWidget2)
        self.ResultsTable.setObjectName("ResultsTable")
        self.gridLayout_6.addWidget(self.ResultsTable, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 2, 0, 1, 1)

        self.retranslateUi(DialogRunAUSTAL2000)
        self.Configuration_toolBox.setCurrentIndex(1)
        self.output_modules_tab_widget.setCurrentIndex(-1)
        self.visualization_modules_tab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(DialogRunAUSTAL2000)

    def retranslateUi(self, DialogRunAUSTAL2000):
        _translate = QtCore.QCoreApplication.translate
        DialogRunAUSTAL2000.setWindowTitle(_translate("DialogRunAUSTAL2000", "OpenALAQS - Run AUSTAL2000"))
        self.RunA2K.setText(_translate("DialogRunAUSTAL2000", "Run AUSTAL2000"))
        self.label.setText(_translate("DialogRunAUSTAL2000", "Select AUSTAL2000 file:"))
        self.pushButtonBrowse_a2k.setText(_translate("DialogRunAUSTAL2000", "Browse"))
        self.label_2.setText(_translate("DialogRunAUSTAL2000", "Select working directory:"))
        self.pushButtonBrowse_work_dir.setText(_translate("DialogRunAUSTAL2000", "Browse"))
        self.label_3.setText(_translate("DialogRunAUSTAL2000", "Options:"))
        self.radioButton.setText(_translate("DialogRunAUSTAL2000", "-D"))
        self.label_query_results.setText(_translate("DialogRunAUSTAL2000", "Query Results"))
        self.label_modules.setText(_translate("DialogRunAUSTAL2000", "Modules:"))
        self.Configuration_toolBox.setItemText(self.Configuration_toolBox.indexOf(self.output_modules_page), _translate("DialogRunAUSTAL2000", "Output Modules"))
        self.Configuration_toolBox.setItemText(self.Configuration_toolBox.indexOf(self.visualisation_modules_page), _translate("DialogRunAUSTAL2000", "Visualization Modules"))
        self.alaqs_output_file.setText(_translate("DialogRunAUSTAL2000", "Select ALAQS output file:"))
        self.pushButtonBrowse_alaqs.setText(_translate("DialogRunAUSTAL2000", "Browse"))
        self.CancelButton.setText(_translate("DialogRunAUSTAL2000", "Close"))
        self.VisualiseResults.setText(_translate("DialogRunAUSTAL2000", "Visualise Results"))
        self.PlotTimeSeries.setText(_translate("DialogRunAUSTAL2000", "Plot timeseries"))
        self.ResultsTable.setText(_translate("DialogRunAUSTAL2000", "Results table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogRunAUSTAL2000 = QtWidgets.QDialog()
    ui = Ui_DialogRunAUSTAL2000()
    ui.setupUi(DialogRunAUSTAL2000)
    DialogRunAUSTAL2000.show()
    sys.exit(app.exec_())
