# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_taxiway_routes.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaxiRoutesDialog(object):
    def setupUi(self, TaxiRoutesDialog):
        TaxiRoutesDialog.setObjectName("TaxiRoutesDialog")
        TaxiRoutesDialog.resize(584, 499)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(TaxiRoutesDialog)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tabWidget_2 = QtWidgets.QTabWidget(TaxiRoutesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.routes = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routes.sizePolicy().hasHeightForWidth())
        self.routes.setSizePolicy(sizePolicy)
        self.routes.setObjectName("routes")
        self.horizontalLayout_3.addWidget(self.routes)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.gate = QtWidgets.QComboBox(self.tab_4)
        self.gate.setObjectName("gate")
        self.verticalLayout_6.addWidget(self.gate)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.runway = QtWidgets.QComboBox(self.tab_4)
        self.runway.setObjectName("runway")
        self.verticalLayout_7.addWidget(self.runway)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.arrdep = QtWidgets.QComboBox(self.tab_4)
        self.arrdep.setObjectName("arrdep")
        self.verticalLayout_9.addWidget(self.arrdep)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.instance = QtWidgets.QComboBox(self.tab_4)
        self.instance.setObjectName("instance")
        self.verticalLayout_8.addWidget(self.instance)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.taxiway_route_name = QtWidgets.QLabel(self.tab_4)
        self.taxiway_route_name.setObjectName("taxiway_route_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.taxiway_route_name)
        self.create = QtWidgets.QPushButton(self.tab_4)
        self.create.setObjectName("create")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.create)
        self.verticalLayout_11.addLayout(self.formLayout_2)
        self.verticalLayout_15.addLayout(self.verticalLayout_11)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_16.addWidget(self.tabWidget_2)
        self.verticalLayout_13.addLayout(self.verticalLayout_16)
        self.tabWidget = QtWidgets.QTabWidget(TaxiRoutesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.taxiway_segments = QtWidgets.QTableWidget(self.tab)
        self.taxiway_segments.setColumnCount(1)
        self.taxiway_segments.setObjectName("taxiway_segments")
        self.taxiway_segments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.taxiway_segments.setHorizontalHeaderItem(0, item)
        self.taxiway_segments.horizontalHeader().setStretchLastSection(True)
        self.taxiway_segments.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_10.addWidget(self.taxiway_segments)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.available_ac_groups = QtWidgets.QTableWidget(self.tab_2)
        self.available_ac_groups.setObjectName("available_ac_groups")
        self.available_ac_groups.setColumnCount(0)
        self.available_ac_groups.setRowCount(0)
        self.available_ac_groups.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.available_ac_groups)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.add_ac_group = QtWidgets.QPushButton(self.tab_2)
        self.add_ac_group.setObjectName("add_ac_group")
        self.verticalLayout_3.addWidget(self.add_ac_group)
        self.delete_ac_group = QtWidgets.QPushButton(self.tab_2)
        self.delete_ac_group.setObjectName("delete_ac_group")
        self.verticalLayout_3.addWidget(self.delete_ac_group)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.selected_ac_groups = QtWidgets.QTableWidget(self.tab_2)
        self.selected_ac_groups.setObjectName("selected_ac_groups")
        self.selected_ac_groups.setColumnCount(0)
        self.selected_ac_groups.setRowCount(0)
        self.selected_ac_groups.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.selected_ac_groups)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_13.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.delete_route = QtWidgets.QPushButton(TaxiRoutesDialog)
        self.delete_route.setObjectName("delete_route")
        self.horizontalLayout.addWidget(self.delete_route)
        self.clear_route = QtWidgets.QPushButton(TaxiRoutesDialog)
        self.clear_route.setObjectName("clear_route")
        self.horizontalLayout.addWidget(self.clear_route)
        self.save_route = QtWidgets.QPushButton(TaxiRoutesDialog)
        self.save_route.setObjectName("save_route")
        self.horizontalLayout.addWidget(self.save_route)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.close_button = QtWidgets.QPushButton(TaxiRoutesDialog)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_13.addLayout(self.verticalLayout)

        self.retranslateUi(TaxiRoutesDialog)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TaxiRoutesDialog)
        TaxiRoutesDialog.setTabOrder(self.gate, self.runway)
        TaxiRoutesDialog.setTabOrder(self.runway, self.instance)
        TaxiRoutesDialog.setTabOrder(self.instance, self.tabWidget)
        TaxiRoutesDialog.setTabOrder(self.tabWidget, self.taxiway_segments)
        TaxiRoutesDialog.setTabOrder(self.taxiway_segments, self.delete_route)
        TaxiRoutesDialog.setTabOrder(self.delete_route, self.clear_route)
        TaxiRoutesDialog.setTabOrder(self.clear_route, self.save_route)
        TaxiRoutesDialog.setTabOrder(self.save_route, self.close_button)
        TaxiRoutesDialog.setTabOrder(self.close_button, self.available_ac_groups)
        TaxiRoutesDialog.setTabOrder(self.available_ac_groups, self.add_ac_group)
        TaxiRoutesDialog.setTabOrder(self.add_ac_group, self.delete_ac_group)
        TaxiRoutesDialog.setTabOrder(self.delete_ac_group, self.selected_ac_groups)
        TaxiRoutesDialog.setTabOrder(self.selected_ac_groups, self.arrdep)

    def retranslateUi(self, TaxiRoutesDialog):
        _translate = QtCore.QCoreApplication.translate
        TaxiRoutesDialog.setWindowTitle(_translate("TaxiRoutesDialog", "OpenALAQS - Taxiway Routes Editor"))
        self.label_5.setText(_translate("TaxiRoutesDialog", "Route ID:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("TaxiRoutesDialog", "Import existing route"))
        self.label.setText(_translate("TaxiRoutesDialog", "Gate"))
        self.label_2.setText(_translate("TaxiRoutesDialog", "Runway"))
        self.label_4.setText(_translate("TaxiRoutesDialog", "Arr/Dep"))
        self.label_3.setText(_translate("TaxiRoutesDialog", "Instance"))
        self.label_8.setText(_translate("TaxiRoutesDialog", "Name Preview:"))
        self.taxiway_route_name.setText(_translate("TaxiRoutesDialog", "None"))
        self.create.setText(_translate("TaxiRoutesDialog", "Create New Route"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("TaxiRoutesDialog", "Create new route"))
        self.taxiway_segments.setToolTip(_translate("TaxiRoutesDialog", "Use the QGIS selection tools to update the list of taxiway segments that belong to particular route."))
        item = self.taxiway_segments.horizontalHeaderItem(0)
        item.setText(_translate("TaxiRoutesDialog", "Taxiway Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TaxiRoutesDialog", "Taxiways"))
        self.label_6.setText(_translate("TaxiRoutesDialog", "Available"))
        self.add_ac_group.setText(_translate("TaxiRoutesDialog", ">"))
        self.delete_ac_group.setText(_translate("TaxiRoutesDialog", "<"))
        self.label_7.setText(_translate("TaxiRoutesDialog", "Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TaxiRoutesDialog", "Aircraft Groups"))
        self.delete_route.setText(_translate("TaxiRoutesDialog", "Delete Route"))
        self.clear_route.setText(_translate("TaxiRoutesDialog", "Clear Route"))
        self.save_route.setText(_translate("TaxiRoutesDialog", "Save Route"))
        self.close_button.setText(_translate("TaxiRoutesDialog", "Close"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaxiRoutesDialog = QtWidgets.QDialog()
    ui = Ui_TaxiRoutesDialog()
    ui.setupUi(TaxiRoutesDialog)
    TaxiRoutesDialog.show()
    sys.exit(app.exec_())
