on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      OSGEO_USERNAME: ${{ secrets.OSGEO_USERNAME }}
      OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci>=2.8.6

      - name: Release
        run: |
          VERSION=${{ github.ref_name }}
          RELEASE_TAG=${GITHUB_REF##*/}
          qgis-plugin-ci release ${VERSION} \
          --release-tag ${RELEASE_TAG} \
          --github-token ${{ secrets.GITHUB_TOKEN }} # \
          # --osgeo-username ${OSGEO_USERNAME} \
          # --osgeo-password ${OSGEO_PASSWORD}
